spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres

server:
  port: 8082
  servlet:
    context-path: /api/v1/shop